### ISSUE TITLE
`UInt::{ct_div_rem, ct_reduce}` are not constant-time

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/crypto-bigint#116]
As noted in #115, both of these functions compute values and then pass them as the `rhs` to `UInt::shl_vartime`.

- https://github.com/RustCrypto/crypto-bigint/blob/ed8d96b/src/uint/div.rs#L24
- https://github.com/RustCrypto/crypto-bigint/blob/ed8d96b/src/uint/div.rs#L63

cc @andrewwhitehead @mikelodder7

**Comment by mikelodder7** [comment]
On line https://github.com/RustCrypto/crypto-bigint/blob/ed8d96be88ea4e1a970f5fcc3ce5cae85113addb/src/uint/div.rs#L15

it specifically says it’s variable wrt the divider. What is the expected output?

**Comment by mikelodder7** [comment]
Is the comment misleading

**Comment by tarcieri** [comment]
The issue is even if `rhs` is constant, it's still variable time with respect to `self`, due to this line:

https://github.com/RustCrypto/crypto-bigint/blob/ed8d96be88ea4e1a970f5fcc3ce5cae85113addb/src/uint/div.rs#L20

See this comment: https://github.com/RustCrypto/crypto-bigint/pull/115#issuecomment-1227579652
