### ISSUE TITLE
Diverging from primitive behavior in overflowing shift

### ISSUE THREAD

**Issue by elichai** [RustCrypto/crypto-bigint#121]
The rust docs say the following about overflowing shift:
> If the shift value is too large, then value is masked (N-1) where N is the number of bits, and this value is then used to perform the shift.
(Source: https://doc.rust-lang.org/std/primitive.u64.html#method.overflowing_shl)
And you can see this via the following code:
```rust
#[allow(arithmetic_overflow)]
fn main() {
    let a: u64 = 500;
    let b = a << 119;
    println!("{}", b);
}
```
Which prints `18014398509481984000`.

On the other hand in the implementation here zeros will be returned: https://github.com/RustCrypto/crypto-bigint/blob/36dbb69a73cfdba1eef90e10a8424cde39602e3b/src/uint/shl.rs#L18

**Comment by tarcieri** [comment]
cc @mikelodder7

**Comment by elichai** [comment]
FYI to achieve the same behavior as libstd we can just add `n = n % (Limb::BIT_SIZE * LIMBS)` at the start of that function
