### ISSUE TITLE
split is implemented for U192 which doesn't seem to be correct on 64-bit platforms

### ISSUE THREAD

**Issue by haslersn** [RustCrypto/crypto-bigint#138]
Reading through some code, I unrelatedly noticed that `pub const fn split(&self)` is unconditionally implemented for `U192`. This doesn't seem to be correct on 64-bit platforms where `U192` has an odd number of limbs.

**Comment by tarcieri** [comment]
On a 64-bit platform, U192 will be represented as 3 x 64-bit limbs. But why are you suggesting that's a problem? There is currently no invariant which says the number of limbs must be an even number.

**Comment by haslersn** [comment]
It looks like the `split` implementation splits it into two `U64`s. Though I'm not sure, as I didn't test it.

**Comment by tarcieri** [comment]
Aah sorry, now I see the issue. Yes, that does seem problematic.

**Comment by tarcieri** [comment]
As of the latest release, this is impl'd by the `impl_uint_concat_split_even!` macro: https://docs.rs/crypto-bigint/latest/src/crypto_bigint/uint/extra_sizes.rs.html#114-160

If I understand correctly, there should be two impls of `fn split`: one which splits into `(U128, U64)`, and another which splits into `(U64, U128)`, although the associated documentation is completely unreadable: https://docs.rs/crypto-bigint/latest/crypto_bigint/type.U192.html#method.split

cc @ycscaly

**Comment by ycscaly** [comment]
> As of the latest release, this is impl'd by the `impl_uint_concat_split_even!` macro: https://docs.rs/crypto-bigint/latest/src/crypto_bigint/uint/extra_sizes.rs.html#114-160
> 
> If I understand correctly, there should be two impls of `fn split`: one which splits into `(U128, U64)`, and another which splits into `(U64, U128)`, although the associated documentation is completely unreadable: https://docs.rs/crypto-bigint/latest/crypto_bigint/type.U192.html#method.split
> 
> cc @ycscaly

Yeah that's how it should be, is this still an issue?

**Comment by tarcieri** [comment]
I think this can be closed
