### ISSUE TITLE
How to Calculate the Modular Multiplication of Three Specified Numbers？

### ISSUE THREAD

**Issue by CrayfishGo** [RustCrypto/crypto-bigint#150]
Here I have three numbers
```rust
    let p = U256::from_be_hex("FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFF");
    let a = U256::from_be_hex("FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFC");
    let b = U256::from_be_hex("28E9FA9E9D9F5E344D5A9E4BCF6509A7F39789F515AB8F92DDBCBD414D940E93");

```
So how to calculate `(a * b) mod p`?

I found this function:
```rust
pub const fn mul_mod_special(&self, rhs: &Self, c: Limb) -> Self {
   ... 
}

```

But I don't know how to determine the value of parameter `c`。

Could you help me?

**Comment by tarcieri** [comment]
This requires features which are unreleased and undocumented at the moment.

If `p` is fixed at compile-time you can use:

https://github.com/RustCrypto/crypto-bigint/blob/7052861/src/uint/modular/constant_mod/const_mul.rs#L10-L13

...or if it's only known at runtime:

https://github.com/RustCrypto/crypto-bigint/blob/7052861/src/uint/modular/runtime_mod/runtime_mul.rs#L11-L22

**Comment by fjarri** [comment]
This is released, so probably can be closed (although a direct `mul_mod()` method, e.g. working via Barrett reduction, might be convenient in some cases)
