### ISSUE TITLE
Bit-counting API is inconsistent with that of primitive types

### ISSUE THREAD

**Issue by fjarri** [RustCrypto/crypto-bigint#154]
There are several differences between `Uint`/`Limb` and Rust's primitive integer types:
- Bit size of the integer: `Limb::BIT_SIZE`, but `u*::BITS`
- Type of the above constant: `Limb::BIT_SIZE` is `usize`, but `u*::BITS` is `u32`
- Return types of zero/bit counting methods: `Limb/Uint::bits()` is `usize`, but `u*::leading_zeros()/trailing_zeros()` is `u32`

Unless there was some specific reason these choices were made, perhaps it makes sense to mimic the existing standard lib API.

**Comment by tarcieri** [comment]
Agreed, would suggest aligning with the primitives in #153
