### ISSUE TITLE
`const_residue` doesn't seem to work outside of crate

### ISSUE THREAD

**Issue by olabiniV2** [RustCrypto/crypto-bigint#191]
(Forgive me if this is an obvious problem based on my lack of Rust experience).

I'm trying to use the modular exp support recently added, but I'm running in to a problem with const_residue. Specifically, I do this:

```rust
impl_modulus!(PMod, U1536, P_STR);
```
where `P_STR` contains the hex string for the modulus. Then, in a test, I do:

```rust
let base = const_residue!(G1, PMod);
```

where `G1` is a big int of the same size as the modulus. However, this leads to a failure saying "module `uint` is private". Specifically:

```
error[E0603]: module `uint` is private
   --> /home/amnesia/Persistent/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-bigint-0.5.0/src/uint/modular/constant_mod/macros.rs:48:17
    |
48  |         $crate::uint::modular::constant_mod::Residue::<$modulus, { $modulus::LIMBS }>::new(
    |                 ^^^^ private module
    |
note: the module `uint` is defined here
   --> /home/amnesia/Persistent/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-bigint-0.5.0/src/lib.rs:167:1
    |
167 | mod uint;
    | ^^^^^^^^
```

**Comment by tarcieri** [comment]
It's most likely a bug. It's a new feature and we've had similar issues with other macros: #172

**Comment by olabiniV2** [comment]
I opened PR #192 which fixes the problem for me. I also added a small test to make sure the macro compiles from outside the crate.

**Comment by olabiniV2** [comment]
(It doesn't pass rustfmt - I'll fix and push)

**Comment by olabiniV2** [comment]
OK, #193 has been opened and passes all checks.
