### ISSUE TITLE
rem function doesn't compute remainder

### ISSUE THREAD

**Issue by kayabaNerve** [RustCrypto/crypto-bigint#198]
I updated https://github.com/serai-dex/serai/blob/develop/crypto/dalek-ff-group/src/field.rs to v0.5, replacing the two `.reduce` calls with rem calls.  I now have a test failure where 1 * 1, which should equal 1, is actually 26. It seems to me 0.5's rem is critically broken.

**Comment by tarcieri** [comment]
That is indeed a serious issue if true.

Would you mind opening a PR with a failing regression test?

**Comment by kayabaNerve** [comment]
Bah. Never mind. I assumed `rem` was the issue since it was the only change needed for compilation. It's actually that U512::from used to be hi, lo, and now it's lo, hi (#183/final note in https://github.com/RustCrypto/crypto-bigint/pull/188). Sorry for the misdiagnosis.

**Comment by tarcieri** [comment]
Aah yeah, sorry, those changes to the tuple ordering are really annoying and should probably be better documented in the CHANGELOG

**Comment by kayabaNerve** [comment]
I am happy it's no longer inconsistent though.
