### ISSUE TITLE
Conversions between different Uxxx types (e.g. U128 to U384)

### ISSUE THREAD

**Issue by ycscaly** [RustCrypto/crypto-bigint#220]
There are times when you need to convert one type to a larger one. Now, this has to be done manually e.g. like this:
```rust
let u: U128 = transcript.challenge(b"u");

let u: U256 = U128::ZERO.concat(&u);
let u: U512 = U256::ZERO.concat(&u);
let u: U1024 = U512::ZERO.concat(&u);
let u: U2048 = U1024::ZERO.concat(&u);
let u: U4096 = U2048::ZERO.concat(&u);
```

What I would have wished to have is an API like this:
```rust
let u: U128 = transcript.challenge(b"u");
let u: U4096 = u.to_u4096;
```

**Comment by andrewwhitehead** [comment]
You should be able to do this with `resize`:

```rs
let u: U128 = transcript.challenge(b"u");
let u: U4096 = u.resize();
```

**Comment by ycscaly** [comment]
> You should be able to do this with `resize`:
> 
> ```rust
> let u: U128 = transcript.challenge(b"u");
> let u: U4096 = u.resize();
> ```

That's perfect, thank you!
