### ISSUE TITLE
Concatenation of different sizes Uint<>s

### ISSUE THREAD

**Issue by ycscaly** [RustCrypto/crypto-bigint#225]
Another missing cross-size functionality is concatenation. It is also a requirement to implement cross-sizes multiplication

**Comment by tarcieri** [comment]
Have you considered upcasting one of the operands prior to multiplication?

**Comment by ycscaly** [comment]
> Have you considered upcasting one of the operands prior to multiplication?

I have, but that's slower (constant-timeness means that e.g. a 4096-bit * 128-bit is like a 4096-bit * 4096-bit this way) and also yields wrong-sized input (same example would yield 8192-bit instead of 4224-bit) which is even worse.

So I definitely need this

**Comment by kayabaNerve** [comment]
I'd appreciate this. half-width multiplications are very useful in ECC.

**Comment by ycscaly** [comment]
I believe #253 resolves this :)
