### ISSUE TITLE
Add missing Uint<> types/sizes

### ISSUE THREAD

**Issue by ycscaly** [RustCrypto/crypto-bigint#228]
In my code, I am using types that represent the multiplication of two different already existing types (e.g. `U4096` and `U256`). However, their concatenated type is missing (e.g. `U4352`).

I could open a PR that adds just the types that are missing for my specific use-case; however, I thought the fact I needed to add these types would mean sometime in the future another consumer would need to add their own missing types for similar reasons etc. and it would be better to solve it once-and-for-all, if possible.

So my actual suggestion is to simply add all sizes between 64-bit and 8192-bit that are multiplication of the limb size, i.e. 64-bit (U64, U128, ... U8128 , U8192). @tarcieri thoughts?

**Comment by tarcieri** [comment]
The more sizes we add, the more it harms compile times.

I guess I'd be okay with them being feature gated.

**Comment by ycscaly** [comment]
> The more sizes we add, the more it harms compile times.
> 
> I guess I'd be okay with them being feature gated.

under `extra_trait_impls` or a seperate feature?

**Comment by tarcieri** [comment]
Maybe something like `extra-sizes`

**Comment by Fethbita** [comment]
I also came across this issue with `U6144` numbers multiplying up to a 12k number, which does not exist. What is the recommended way to add new types if not a PR?
