### ISSUE TITLE
`DynResidue` exponentiation of larger `Uint`s

### ISSUE THREAD

**Issue by ycscaly** [RustCrypto/crypto-bigint#234]
I need to raise a `DynResidue<U4096::LIMBS>` by a `U4352`. There is currently no way for me to do that.
What I could do is:
```rust
impl Pow<U4352> for DynResidue<U4096::LIMBS> {
    fn pow(&self, exponent: &U4352) -> Self {
        let (exponent_hi, exponent_lo): (U4096, U4096) = <U4096 as Concat>::Output::from(exponent).split();

        let lo = self.pow(&exponent_lo);
        let hi = (self.pow(&U4096::MAX) * self).pow_bounded_exp(&exponent_hi, U4352::BITS - U4096::BITS);

        lo * hi
    }
}
```
Or, in a more generalized form:
```rust
macro_rules! impl_pow_cross_sizes {
    (($first_type:ident, $first_bits:expr), ($(($second_type:ident, $second_bits:expr)),+ $(,)?)) => {
        $(
            impl Pow<$second_type> for DynResidue<{nlimbs!($first_bits)}> {
                fn pow(&self, exponent: &$second_type) -> DynResidue<{nlimbs!($first_bits)}> {
                    let mut i = 0;
                    let mut shifted_base = self.clone();
                    let mut res = DynResidue::<{nlimbs!($first_bits)}>::one(self.params().clone());

                    while i < $second_bits / $first_bits {
                        let mut limbs = [Limb::ZERO; nlimbs!($first_bits)];
                        let mut j = 0;

                        while j < nlimbs!($first_bits) {
                            limbs[j] = exponent.limbs[i*nlimbs!($first_bits) + j];
                            j += 1;
                        }

                        let exponent_i: $first_type = Uint { limbs }; // The ith part of the exponent
                        res *= shifted_base.pow(&exponent_i);
                        shifted_base = shifted_base.pow(&$first_type::MAX) * shifted_base; // Shift by Self::bits

                        i += 1;
                    }

                    let mut limbs = [Limb::ZERO; nlimbs!($second_bits % $first_bits)];
                    let mut j = 0;

                    while j < nlimbs!($second_bits % $first_bits) {
                        limbs[j] = exponent.limbs[i*nlimbs!($first_bits) + j];
                        j += 1;
                    }

                    let part: $first_type = Uint { limbs }.into();

                    res *= shifted_base.pow_bounded_exp(
                        &part,
                        $second_bits % $first_bits,
                    );

                    res
               }
            }
        )+
    };
}
```
Now, this should be a working approach and I could do a PR for this. 

However, it feels non-optimal; I'd have wanted the exponentiation (i.e. Montgomery reduction) algorithm to factor in the different sizes instead of wrapping around the currently existing API (similarly to[ what I did with `mul_wide`](https://github.com/RustCrypto/crypto-bigint/blob/cc778433f026d2aa6bafb1839608c50c49b74b84/src/uint/mul.rs#L20)). But I don't know how to do that, or whether it could be done.

What approach should be taken here?

**Comment by tarcieri** [comment]
I think the general solution to all of these "cross size" problems is to write the impls generically so different sized values can be supported, rather than trying to generate a combinatorial explosion of size-by-size impls

**Comment by ycscaly** [comment]
> I think the general solution to all of these "cross size" problems is to write the impls generically so different sized values can be supported, rather than trying to generate a combinatorial explosion of size-by-size impls with macros

How do you suggest doing so? LIke I did with `mul_wide`? can that be done with `pow`?

**Comment by tarcieri** [comment]
Yes, it might require `generic_const_exprs`. I'm not sure. You'd have to try it.

**Comment by ycscaly** [comment]
> Yes, it might require `generic_const_exprs`. I'm not sure. You'd have to try it.

I have tried it and it required it.

So what's the game plan here? I've gotten `extra-trait-impls` to a mergable situation afaik, I implemented all your requests - are we going to merge?

And if so, should I also create a similar PR for `Pow`?

**Comment by tarcieri** [comment]
Give me some time to re-review the PRs

**Comment by ycscaly** [comment]
> Give me some time to re-review the PRs

Of course. Should I open a similar one for `Pow`, or should we delay this discussion?

**Comment by ycscaly** [comment]
> > I have tried it and it required it.
> 
> Also what did you try and why was it required?

I tried to implement `Concat` between sizes in a generic way, i.e. with an additional `RHS_LIMBS` const generic parameter, and it failed due to the missing `generic_const_exprs`.

We had a discussion about it in the `extra-trait-impls` PR, and I explained it [there](https://github.com/RustCrypto/crypto-bigint/pull/230/files#r1187590117) .

**Comment by tarcieri** [comment]
If you can make the generic implementation work by adding a `nightly` feature, I guess that would be OK.

I'm not sure how stable that's going to be though.

**Comment by ycscaly** [comment]
> If you can make the generic implementation work by adding a `nightly` feature, I guess that would be OK.
> 
> I'm not sure how stable that's going to be though.

No I can't use unstable Rust. My project is security-oriented and I can't risk that
