### ISSUE TITLE
Expose Residue internals?

### ISSUE THREAD

**Issue by andrewwhitehead** [RustCrypto/crypto-bigint#236]
At the moment I can't make use of the (Dyn)Residue type as there's no way to access the inner value in Montgomery form, or to create a Residue from such a value. This restricts the ability to perform operations which aren't supported by the type. For example, if I have a modulus with one or more empty leading bits, a wrapping type might perform addition and doubling without a carry (and with a bitshift). But this isn't possible if I have to convert back and forth to canonical form.

**Comment by tarcieri** [comment]
Perhaps an `as_montgomery` method which returns a reference to the inner value?

**Comment by andrewwhitehead** [comment]
Yup I think that would be sufficient, perhaps `as_montgomery_mut`?
