### ISSUE TITLE
0.5.x breaks JetBrains IDEs

### ISSUE THREAD

**Issue by indygreg** [RustCrypto/crypto-bigint#284]
I thought you may like to know that the 0.5.3 (and probably other 0.5.x) releases of this crate is causing JetBrains' Rust integration to crash and make the IDE experience horrible. More info at https://youtrack.jetbrains.com/issue/RUST-11841/Can-not-run-nested-type-inference-types-and-highlighting-in-the-code-are-not-displayed.

There are (predictably) people downgrading to 0.4 and holding back other RustCrypto upgrades to keep their IDEs working.

Feel free to close this issue as non-actionable (since it is almost certainly a JetBrains IDE bug). But it looks like the bug has been going on for a few months and who knows when JetBrains will fix it.

**Comment by tarcieri** [comment]
Odd. Much of it was written in IntelliJ. Can’t say I’ve experienced that.

**Comment by makavity** [comment]
Already fixed
https://youtrack.jetbrains.com/issue/RUST-11763
