### ISSUE TITLE
`random_mod` can take a very long time

### ISSUE THREAD

**Issue by Sc00bz** [RustCrypto/crypto-bigint#3]
https://github.com/RustCrypto/utils/blob/710abc8c83a13def1c01958909405976f915e5a5/crypto-bigint/src/uint/rand.rs#L34-L42

If `modulus` is small compared to the full size ("number of limbs * size of limb") then it can take "forever".

The correct method is to mask off the top bits of the random number to match the size of `modulus`. This leads to a worst case of a 50% chance of failing and needing to generate another random number. The average for this worst case is needing to generate 2 random numbers.

**Comment by tarcieri** [comment]
Regarding a non-zero modulus, we recently added a `NonZero` wrapper (#13) which can ensure the modulus is non-zero at the type level, although switching to it would be a breaking change.

It might be good to make some breaking changes soon though and release a v0.3.

**Comment by Sc00bz** [comment]
P.S. That `modulo` can take a very long time and literally forever if used for after multiply. While also not being time constant (leaks x from x\*divisor+remainder, but in the case of random x is worthless).
