### ISSUE TITLE
Use wide arithmetic in `CtChoice`

### ISSUE THREAD

**Issue by fjarri** [RustCrypto/crypto-bigint#418]
We are currently using two different algorithms for constant-time comparison of `Word`s:
- the one in `CtChoice` (e.g. `from_word_lt()`), using arithmetic on `Word`
- the one in `Limb`'s implementations of `subtle` traits, using arithmetic on `WideWord`

The latter seems to be faster than the former (from the `limb.rs` benchmarks). We should use just one version of the algorithms both for performance reasons, and for simplicity. Probably should be implemented in `CtChoice`, and the `Limb`'s impls should call it and convert `CtChoice` to `Choice`.

Also there is a third way to do it, by using the built-in `overflowing_sub()` method instead of `sbb`. Seems to be producing branch-free assembly, according to Godbolt - how safe is it?

**Comment by tarcieri** [comment]
It seems like `overflowing_sub` would be fine for this use case, as would using `CtChoice` and converting to `Choice` for the purposes of `Limb`

**Comment by fjarri** [comment]
After some tests on Godbolt it seems `overflowing_sub()` when used this way compiles down to `cmp` on x86 - same as the current `sbb` approach, or in fact just directly casting `(x < y) as Word`. So the question is, do we consider `cmp` constant time? If not, we need to use the within-`Word` algorithm from Hacker's Delight (currently in `ConstChoice::from_word_lt()`.

**Comment by fjarri** [comment]
To summarize:

- for all the architectures `lt1` is identical to `lt4`
- `wasm32-unknown-unknown`: all but `lt2` use `lt_u` operand. So `lt2` is at least as safe as the rest and possibly safer, depending on how `lt_u` is actually implemented.
- `aarch64-apple-darwin`: `lt3` is almost identical to `lt1`, all but `lt2` use `cmp` operand. So `lt2` again is as at least as safe as the rest and possibly safer, depending on how `cmp` is implemented.
- `i686-unknown-linux-gnu`: `lt3` is almost identical to `lt1`, all functions use `cmp` operand. So we might as well use `lt1` or `lt4` here without jumping through any additional hoops.
- `thumbv7em-none-eabi`: `lt3` is almost identical to `lt1`, all functions use subtract-with-carry (`sbcs`). So no difference between the functions.

That is, it is probably okay to just use `lt4`, and if we want to be extra-safe, we can use `lt2`.

**Comment by tarcieri** [comment]
I guess I'll need to investigate why the `sbb` approach impacts performance so much on #415.

The worries with `cmp` were related to things like speculative execution and a general desire to avoid anything branch-related, though perhaps that's not an issue without a corresponding jump instruction.
