### ISSUE TITLE
Inverse `Even` modulus

### ISSUE THREAD

**Issue by pinkforest** [RustCrypto/crypto-bigint#591]
RSA has `Even` inverse modulus because p-1 for Euler's totient
- https://github.com/RustCrypto/RSA/pull/394/files#r1552977891

But only `Odd` is provided via BoxedUint::inv_odd_mod - similar to BY-GCD
- #590 

I see @fjarri asked similar stuff before in math stackexchange:

- https://math.stackexchange.com/questions/4631776/modular-inverse-with-composite-even-modulus/4633908#4633908
- https://math.stackexchange.com/questions/3434557/how-to-solve-a-linear-congruence-8n9-equiv-0-pmod-1163/3434593#3434593

**Comment by fjarri** [comment]
I needed it for the same thing (inversion modulo totient), and the answer to that M.SE question is implemented in https://docs.rs/crypto-bigint/latest/crypto_bigint/struct.Uint.html#method.inv_mod . Not sure why it wasn't extended to `BoxedUint`, but it's probably quite straightforward.

**Comment by tarcieri** [comment]
Indeed that should be easy to port over

**Comment by tarcieri** [comment]
Fixed in #594
