### ISSUE TITLE
Support for creating `BoxedMontyParams` from `ConstMontyParams`

### ISSUE THREAD

**Issue by jjteo74** [RustCrypto/crypto-bigint#593]
Version: `0.6.0-pre.12`.

I am trying to define pre-computed SSH DH groups 1 and 14-18 parameters using `ConstMontyParams` because groups 15-18 take a long time to compute--more than 5s (debug) for group 18 with modulus U8192 on my laptop. And to do DH shared secret computation in `BoxedUint` for good hygiene.

However, there doesn't seem to be a way to create `BoxedMontyParams` from either `MontyParams` or `ConstMontyParams` so the current way forward is to use `OnceLock<Arc<BoxedMontyParams>>`, but this is not ideal.

Is there a way to pre-compute `BoxedMontyParams`?

**Comment by tarcieri** [comment]
We don't yet have an easy `From` conversion for this but it should be easy to add

**Comment by jjteo74** [comment]
Thanks for the reply.
