### ISSUE TITLE
`Monty::new` takes values, but impl takes ref

### ISSUE THREAD

**Issue by dvdplm** [RustCrypto/crypto-bigint#599]
The `Monty` trait's [`new` method](https://github.com/RustCrypto/crypto-bigint/blob/6ccbe7412ffbb041e79c520be623af330ee8730f/src/traits.rs#L800) takes its arguments by value, but [the implementation for `MontyForm`](https://github.com/RustCrypto/crypto-bigint/blob/6ccbe7412ffbb041e79c520be623af330ee8730f/src/modular/monty_form.rs#L243) uses references when calling into [`MontyForm::new`](https://github.com/RustCrypto/crypto-bigint/blob/6ccbe7412ffbb041e79c520be623af330ee8730f/src/modular/monty_form.rs#L156).

What are your thoughts on changing the trait in v0.6 to take a reference as well? The `new` method only ever need read access to the data so why impose a clone/copy on users if they need to keep using their `Integer`?

Sort of like so:
```
src/traits.rs --- Rust
799     /// Convert the value into the representation using precomputed data.
800     fn new(value: &Self::Integer, params: Self::Params) -> Self;
801 

src/modular/monty_form.rs --- Rust
243     fn new(value: &Self::Integer, params: Self::Params) -> Self {
244         MontyForm::new(value, params)
245     } 

```

**Comment by tarcieri** [comment]
Yeah, I think it would make sense for it to borrow
