### ISSUE TITLE
Remove bounds proliferation for `gcd()`

### ISSUE THREAD

**Issue by fjarri** [RustCrypto/crypto-bigint#633]
I would like to use `gcd_vartime()` in `crypto-primes` whose methods are generic on `T: Integer`. Right now it cannot be done without spelling out an explicit bound `Odd<T>: PrecomputeInverter`, which will be further propagated to the user code if it is generic as well. Is it possible to make it so that just `T: Gcd<Output=T>` is enough? 

It is possible to have a default implementation of `gcd()`/`gcd_vartime()` for `Integer`, based on `rem()`/`rem_vartime()`, even though it will be significantly slower than the Bernstein-Yang one. 

*Edit:* that is, possible for `gcd_vartime()` only. Nevertheless, ideally it should be enough to only have a bound on `Gcd` for the constant-time method.

**Comment by tarcieri** [comment]
> Is it possible to make it so that just T: Gcd<Output=T> is enough?

That should definitely be the goal. Is the issue that it's not currently captured by the `Gcd` trait?

**Comment by fjarri** [comment]
Tried it out, and #636 does make it so only the `Gcd` bound is required. Do you think it is worth adding `gcd_vartime()` to `Integer` (since it's a direct consequence of having `rem_vartime()`), or do you prefer to keep the `Gcd` trait separate?

**Comment by tarcieri** [comment]
It's currently implemented using Bernstein-Yang (I believe you said yourself Euclid with `rem_vartime` is slower, and not constant time with respect to any inputs), so I think it makes sense to leave on the `Gcd` trait.

**Comment by tarcieri** [comment]
Closing this then. Hopefully the `Gcd` bound is acceptable.
