### ISSUE TITLE
Allow doc comments for structs created with `impl_modulus!` macro

### ISSUE THREAD

**Issue by TitouanReal** [RustCrypto/crypto-bigint#662]
The macro `impl_modulus!` generates a structure implementing `ConstMontyParams`.

I would like to expose this structure in an API and would like to document it. However I need the macro to support this and to generate the doc as part of its expansion, from a string I could give to it.

Can this be easily implemented? I would like something like this:

```rust
impl_modulus!(
    MOD,
    Uint<LIMBS>,
    "65b48e8f740f89bffc8ab0d15e3e4c4ab42d083aedc88c425afbfcc69322c9c\
    da7aac6c567f35507516730cc1f0b4f25c2721bf457aca8351b81b90533c6c87b",
    "My documentation for the struct"
);
```

**Comment by tarcieri** [comment]
Does putting a doc comment/attribute immediately above it not work?

**Comment by TitouanReal** [comment]
If I write

```rust
/// my doc
impl_modulus!(
    MOD,
    Uint<LIMBS>,
    "65b48e8f740f89bffc8ab0d15e3e4c4ab42d083aedc88c425afbfcc69322c9c\
    da7aac6c567f35507516730cc1f0b4f25c2721bf457aca8351b81b90533c6c87b"
);
```

Then I get

```shell
warning: unused doc comment
  --> src/csidh_params/csidh_512.rs:12:1
   |
12 | /// my doc
   | ^^^^^^^^^^ rustdoc does not generate documentation for macro invocations
   |
   = help: to document an item produced by a macro, the macro must produce the documentation as part of its expansion
   = note: `#[warn(unused_doc_comments)]` on by default
```

And the struct is not documented by rustdoc.

**Comment by tarcieri** [comment]
okay, we can potentially add an optional extra argument for the documentation string if that makes things easier
