### ISSUE TITLE
`UInt` serialization differs between 64 & 32 bit architectures

### ISSUE THREAD

**Issue by ItayLevyOfficial** [RustCrypto/crypto-bigint#701]
When running this code:
```
let a = Uint::<32>::from_u8(5);
println!("{:?}", base64::encode(serde_json::to_vec(&a).unwrap()));
```
from a 64-bit environment (My mac), I get 
```
"IjA1MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIg=="
```

And when running the exact same code from within a wasm environment (which is 32 bit), I get

```
"IjA1MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAi"
```

Which is twice as short. This is problematic because the server's 64bit's serialization cannot be deserialized by my wasm's front end.

**Comment by erik-3milabs** [comment]
The `32` in `Uint::<32>` tells you that the number of memory words used to represent this unsigned integer is `32`. 
The problem you're encountering is that the size of a memory word is architecture-dependent:
- a 32-bit architecture uses 32-bit words, whereas
- a 64-bit architecture uses 64-bit words.

Assuming the bit-length of your unsigned integer is constant regardless of the environment, I'd recommend you replace `Uint::<32>` with `U2048`. It is the struct that contains a 2048-bit unsigned integer, regardless of the environment.
